package product_p2p.kit.RSA;



/***
 * TEst
 * @author Administrator
 *
 */
public class Test {

	public static void main(String[] args) {
		/*String source = "骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿骆驼与祥子】暗黑世界将哈哈是1jahjksdhjjh1khHKJhjkahkjdhakj jhsajk看哈进口货卡仕达金卡和史可隽加上看黄河科技好看看氨甲苯酸不是abs你们版貌似被  阿斯顿";
		RSAPlugn plugn = new RSAPlugn();
		String shiyaojiami = plugn.encryptionByPrivateKey(source);
		System.out.println("私钥加密："+shiyaojiami);
		String gongyaojiemi = plugn.decryptByPublicKey(shiyaojiami);
		System.out.println("公钥解密："+gongyaojiemi);
		String gongyaojiami = plugn.encryptionByPublicKey(source);
		System.out.println("公钥加密："+gongyaojiami);
		String shiyaojiemi = plugn.decryptByPrivateKey(gongyaojiami);
		System.out.println("私钥解密："+shiyaojiemi);*/
		
	}
}
